FROM node:24-alpine AS builder
WORKDIR /app

COPY .npmrc package.json tsconfig.base.json ./
COPY packages/sdk-frontend packages/sdk-frontend

RUN npm install --workspace=packages/sdk-frontend
RUN npm run build -w packages/sdk-frontend

FROM nginx:alpine

COPY --from=builder /app/packages/sdk-frontend/dist /usr/share/nginx/html/sdk-frontend
COPY nginx.sdk.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
